# Journey for applicant adult

## applicant:adult email notification
* Given the user is on page "p--new-or-existing-application"
* When they answer "Start a new application" to question "q--new-or-existing-application"
* And they "Continue"
* Then the user is on page "p-applicant-fatal-claim"
* Given the user is on page "p-applicant-fatal-claim"
* When they answer "No" to question "q-applicant-fatal-claim"
* And they "Continue"
* Then the user is on page "p--was-the-crime-reported-to-police"
* Given the user is on page "p--was-the-crime-reported-to-police"
* When they answer "Yes" to question "q--was-the-crime-reported-to-police"
* And they "Continue"
* Then the user is on page "p-applicant-has-crime-reference-number"
* Given the user is on page "p-applicant-has-crime-reference-number"
* When they answer "Yes" to question "q-applicant-has-crime-reference-number"
* And they "Continue"
* Then the user is on page "p-applicant-who-are-you-applying-for"
* Given the user is on page "p-applicant-who-are-you-applying-for"
* When they answer "Myself" to question "q-applicant-who-are-you-applying-for"
* And they "Continue"
* Then the user is on page "p-applicant-are-you-18-or-over"
* Given the user is on page "p-applicant-are-you-18-or-over"
* When they answer "Yes" to question "q-applicant-are-you-18-or-over"
* And they "Continue"
* Then the user is on page "p-applicant-british-citizen-or-eu-national"
* When they answer "Yes" to question "q-applicant-british-citizen-or-eu-national"
* And they "Continue"
* Then the user is on page "p--context-applicant-details"
* Given the user is on page "p--context-applicant-details"
* And they "Continue"
* Then the user is on page "p-applicant-confirmation-method"
* Given the user is on page "p-applicant-confirmation-method"
* When they answer "Email" to question "q-applicant-confirmation-method"
* And they answer "here@there.com" to question "q-applicant-enter-your-email-address"
* And they "Continue"
* Then the user is on page "p-applicant-enter-your-name"
* Given the user is on page "p-applicant-enter-your-name"
* When they answer "Miss" to question "q-applicant-title"
* And they answer "Test" to question "q-applicant-first-name"
* And they answer "Testcase" to question "q-applicant-last-name"
* And they "Continue"
* Then the user is on page "p-applicant-have-you-been-known-by-any-other-names"
* Given the user is on page "p-applicant-have-you-been-known-by-any-other-names"
* When they answer "No" to question "q-applicant-have-you-been-known-by-any-other-names"
* And they "Continue"
* Then the user is on page "p-applicant-enter-your-date-of-birth"
* Given the user is on page "p-applicant-enter-your-date-of-birth"
* When they answer "1990-03-31T00:00:00.000Z" to question "q-applicant-enter-your-date-of-birth"
* And they "Continue"
* Then the user is on page "p-applicant-enter-your-address"

